name: Sync Codeforces Data

on:
  schedule:
    # Run daily at 2 AM UTC (can be configured)
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Sync data
      run: |
        curl -X POST "${{ secrets.APP_URL }}/api/sync/all" \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.SYNC_API_KEY }}"
      env:
        APP_URL: ${{ secrets.APP_URL }}
        SYNC_API_KEY: ${{ secrets.SYNC_API_KEY }}
